# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /exam
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis配置
mybatis:
#     搜索指定包别名
#    typeAliasesPackage: com.zhrj.**.entity
#     配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath:mapper/**/*Mapper.xml
#     加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

#mybatis-plus:
#  configuration:
#    #设置当查询结果值为null时，同样映射该查询字段给map。
#    call-setters-on-nulls: true
#    # 下划线转驼峰
#    map-underscore-to-camel-case: true

#logging:
#  level:
#    root: DEBUG
